apiVersion: backup.example.com/v1alpha1
kind: ServiceMonitoring
metadata:
  labels:
    app.kubernetes.io/name: k8s-monitoring-operator
    app.kubernetes.io/managed-by: kustomize
  name: servicemonitoring-sample
spec:
  # TODO(user): Add fields here
